name: Init CI Workflow
on:
  push:
    branches: [ "main" ]

jobs:
  node-build:
    uses: codeparce/ci-workflows/.github/workflows/node-build.yml@main
    with:
      environment: dev
    secrets:
      personal_access_token: ${{ secrets.TERRAFORM_REPO_TOKEN }}